### ISSUE TITLE
Please add inline demos on documentation page

### ISSUE THREAD

**Issue by Koc** [framework7io/framework7-website#150]
It is natural watch live examples when reading docs. But if we opens https://framework7.io/vue/checkbox.html - no any demos present.

For example [Element UI](http://element.eleme.io/#/en-US/component/cascader) docs page displays to user demos first. And only after then we can open listing code or even create small sandbox with this exemple on jsfiddle. It wery useful.

**Comment by nolimits4web** [comment]
Demos here will appear with v3 release
