### ISSUE TITLE
How make touch event affect in pc browser?

### ISSUE THREAD

**Issue by funkyLover** [framework7io/framework7-website#180]
great documentation!

but I get an irrelevant problem.

why the swipe out component in [docs website](http://framework7.io/) can react with touch event in pc browser (chrome)?

**Comment by nolimits4web** [comment]
Framework7 library issues must be opened at relevant repo at https://github.com/framework7io/framework7

**Comment by funkyLover** [comment]
@nolimits4web this is not an issue with Framework7 library...
I am just interested in how [Framework7 documentation](http://framework7.io/) support touch event(swipe out component) when I visit by pc browser
