### ISSUE TITLE
Предложение: расширить документацию по Router Component

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7-website#230]
В https://framework7.io/docs/router-component.html совсем не сказано о том, что компонентом может быть, к примеру. Popup. Информацию об этом можно найти только в блоге: https://blog.framework7.io/mastering-v2-router-958ea2dbd24f в разделе Routable Modals

**Comment by nolimits4web** [comment]
Добавил http://framework7.io/docs/router-component.html#component-root-element
