### ISSUE TITLE
React Documentation for events are missing "on" before each name.

### ISSUE THREAD

**Issue by GimpMaster** [framework7io/framework7-website#281]
I noticed that on the react documentation for any events the function names are not totally correct.

For example on the Page component you have an event called:

pageBeforeIn

but to actually use it you need to use the following: onPageBeforeIn={}

I didn't see any explanation of this difference on the page and I had to figure it out but stepping into the compoent. Is there something I'm missing?

Thanks for your great work!

**Comment by nolimits4web** [comment]
It is mentioned here https://framework7.io/react/react-component-extensions.html#events

**Comment by GimpMaster** [comment]
Thank you. I missed that section at the bottom of that page.
