### ISSUE TITLE
add "air" for mobile & tablet breakpoint

### ISSUE THREAD

**Issue by Arhell** [framework7io/framework7-website#298]
before:
mobile - http://joxi.ru/EA4d0vXtoye7yA
tablet - http://joxi.ru/n2YLp5ZTbBgN1m

after:
mobile - http://joxi.ru/MAjdnlbtjOeMLm
tablet - http://joxi.ru/v29RblXCZwex9A

add more "air"
#297

**Comment by nolimits4web** [comment]
Fixed
