### ISSUE TITLE
Question on "Pull To Refresh" examples

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#302]
I noticed that different code examples are used to show the various versions of the "_Pull To Refresh_" feature that cause different behaviors.

For example, the code `self.items.push` is used in [Kitchen Sink (Core)](https://framework7.io/docs/kitchen-sink.html) and the new element is added **at the end** of those already present.

Instead in the [“Pull From Top”](https://framework7.io/docs/pull-to-refresh.html#examples) and [“Pull From Bottom”](https://framework7.io/docs/pull-to-refresh.html#examples) examples of the page [“Pull To Refresh” (Core)](https://framework7.io/docs/pull-to-refresh.html) the code `$ptrContent.find('ul').prepend(itemHTML)` is used and the new element is added **on top** of those already present.

In the React versions the `items.push` code is used both in [Kitchen Sink](https://framework7.io/react/kitchen-sink.html) and in the [“Page” demo](https://framework7.io/react/page.html#pull-to-refresh) and the new element is added **at the end** of those already present.

In the Vue versions the `self.items.push` code is used both in [Kitchen Sink](https://framework7.io/vue/kitchen-sink.html) and in the [“Page” demo](https://framework7.io/vue/page.html#pull-to-refresh) and the new element is added **at the end** of those already present.

I just wanted to know if this was done to show all the possibilities of this feature or is it unintentional?

Thanks.

**Comment by DAnn2012** [comment]
I tried to edit in **pull-to-refresh.html** of _Kitchen Sink (Core)_

from

`self.items.push`

to

`self.items.unshift`

and now the new elements are added **on top** of the existing ones.

**Comment by nolimits4web** [comment]
It just the examples, and having elements on top or bottom depends only on user content/design requirements, there is no only one and correct way of doing things here

**Comment by DAnn2012** [comment]
I thank you for the explanation.
