### ISSUE TITLE
carbon goes beyond the block

### ISSUE THREAD

**Issue by Arhell** [framework7io/framework7-website#320]
before
![1](https://user-images.githubusercontent.com/26163841/66353849-96e9b700-e952-11e9-992c-a9c4354893d7.jpg)

after fix
![2](https://user-images.githubusercontent.com/26163841/66353858-9f41f200-e952-11e9-8121-54c22fd71504.jpg)

**Comment by nolimits4web** [comment]
Fixed by #321
