### ISSUE TITLE
Mobile preview links 

### ISSUE THREAD

**Issue by Arhell** [framework7io/framework7-website#323]
Hi, preview links goes beyond
before:
![1](https://user-images.githubusercontent.com/26163841/66605936-b46c8a00-ebb9-11e9-9209-32f130312410.jpg)

after:
![2](https://user-images.githubusercontent.com/26163841/66605953-bb939800-ebb9-11e9-9d79-1fa065e56a06.jpg)
#323

**Comment by nolimits4web** [comment]
Fixed by #324
