### ISSUE TITLE
Дергание примеров на сайте в Chrome

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7-website#335]
Вот так выглядит сайт в Chrome на Маке (в остальных браузерах подергивания совсем мелкие): 

https://youtu.be/K1Gy5dTVptk

то ли это произошло после последнего обновления сайта, то ли после того, как мак обновился до Catalina. Кеш сброшен.

Не мешает, просто визуальный баг.

**Comment by Overman775** [comment]
Аналогичная проблема в Хроме под Windows, просто не двигается подложка
![err2](https://user-images.githubusercontent.com/47769319/68986132-419ca180-083e-11ea-9b78-5beda65159c8.gif)

**Comment by nolimits4web** [comment]
Поправил, спасибо
