### ISSUE TITLE
Перекрытие chevron-right списка элементом sortable-handler 

### ISSUE THREAD

**Issue by AlexZubov** [framework7io/framework7-website#338]
При включении сортировки списка типа ist links-list и подобных, где имеется chevron-right, элемент "гамбургер" сортировки накладывается на chevron.
```
<div class="list links-list sortable sortable-tap-hold">
  <ul>
    <li>
      <a href="#">Link Item 1</a>
     <div class="sortable-handler"></div>
    </li>
    <li>
      <a href="#">Link Item 2</a>
     <div class="sortable-handler"></div>
    </li>
    <li>
      <a href="#">Link Item 3</a>
     <div class="sortable-handler"></div>
    </li>
    ...
  </ul>
</div>
```
Предлагаю добавить дополнительный стиль, который решает проблему:
```
.list.sortable.sortable-enabled a.item-link:before {
    visibility: hidden;
}
```

**Comment by nolimits4web** [comment]
Ошибку по основному фреймворку нужно открывать тут https://github.com/framework7io/framework7 + нужно указать конкретно при какой структуре (HTML) возникает ошибка
