### ISSUE TITLE
Add flex-direction- helpers to typography docs

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-website#339]
When using the flexbox helpers, I do not find a way to align vertical properly without assigning "flex-direction: column". But when used in popups, after closing and reopening the popup, it is displayed incorrectly. The helper classes works well, but for column, there is no class today.

**Comment by scriptPilot** [comment]
Thanks, that works. But not as expected, but maybe I expect / do something wrong?

**Result with additional DIV and width / height values - that is how it should look like**

```html
<f7-page>
  <div style="width: 100%; height: 100%;" class="display-flex flex-direction-column justify-content-center align-items-center">
    <f7-block>Text 1</f7-block>
    <f7-block>Text 2</f7-block>
  </div>
</f7-page>
```

<img width="397" alt="Bildschirmfoto 2019-12-03 um 22 21 40" src="https://user-images.githubusercontent.com/19615586/70090917-61dca680-161b-11ea-866e-72422a90577b.png">

**Result when assigning style / class to the f7-page element**

```html
<f7-page style="width: 100%; height: 100%;" class="display-flex flex-direction-column justify-content-center align-items-center">
  <f7-block>Text 1</f7-block>
  <f7-block>Text 2</f7-block>
</f7-page>
```

<img width="403" alt="Bildschirmfoto 2019-12-03 um 22 26 23" src="https://user-images.githubusercontent.com/19615586/70091247-065ee880-161c-11ea-887e-daf5eefacdc4.png">

**And finally - with same result - the code I expect to work**

```html
<f7-page class="display-flex flex-direction-column justify-content-center align-items-center">
  <f7-block>Text 1</f7-block>
  <f7-block>Text 2</f7-block>
</f7-page>
```

**Comment by nolimits4web** [comment]
If you inspect page you will see that there is a page-content element, so better just add custom class for page and these styles to its `.page-content`

**Comment by scriptPilot** [comment]
Thanks. That way it works :-)

**Comment by scriptPilot** [comment]
Oh .. reopened to follow-up docs update.
