### ISSUE TITLE
Dialog: Value of the default closeByBackdropClick parameter

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#348]
The correct value of the default **closeByBackdropClick** parameter

is **True**

https://github.com/framework7io/framework7/blob/440649b1961ec213d354a656c241ede5aa9ef415/src/core/components/dialog/dialog.d.ts#L61-L62

https://github.com/framework7io/framework7-website/blob/067ca2c74fd45c878e1ee9b59429f6a2807a44e5/src/pug/docs/dialog.pug#L93-L96

..or **False** ?

https://github.com/framework7io/framework7/blob/440649b1961ec213d354a656c241ede5aa9ef415/src/core/components/dialog/dialog.js#L17

Thanks.

**Comment by nolimits4web** [comment]
It is `false`, fixed thanks!
