### ISSUE TITLE
Expandable cards leaves background blurred after expanding

### ISSUE THREAD

**Issue by slothstronaut** [framework7io/framework7-website#387]
If you try any of the example "expandable" cards on Mac/Chrome after tapping to expand then tapping to collapse the blurred background applies to the whole screen and blurs all elements.

Not sure if this affects the core library, but the example expandable cards on docs is definitely broken.

Here is a sample screenshot after triggering this condition: https://www.dropbox.com/s/rclswk7pll849l4/Screenshot%202020-05-24%2009.54.22.png?dl=0

**Comment by nolimits4web** [comment]
This is a some Chrome issue and seems like it doesn't happen when demo is running NOT in iframe
