### ISSUE TITLE
Searchbar search Event parameters don't match V5 docs?

### ISSUE THREAD

**Issue by kleiteimc** [framework7io/framework7-website#399]
It appears there was a change between V4 and V5 with searchbar:search element event.

V4.3.1 - framework7.bundle.js at line 26400 has:

$el.trigger('searchbar:search', query, sb.previousQuery);

Which matches the documentation for both V4 and V5 docs.

V5.7.8 - framework7.bundle.js at 28199 has this line of code:

$el.trigger('searchbar:search', { query: query, previousQuery: sb.previousQuery });

V5 searchbar:search event is sending an object as the second parameter which isn't defined in the documentation for V5.

Thanks,
Kris

**Comment by nolimits4web** [comment]
Thanks, fixed
