### ISSUE TITLE
`virtualSlides` or `virtual-slides` for f7 Vue?

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#517]
@nolimits4web A curiosity, in the Vue version the property name in Photo Browser must be reported as `virtualSlides`

https://github.com/framework7io/framework7-website/blob/111c8af323a53882be2cc8af8a5dbf2b1734dc5c/src/pug/vue/photo-browser.pug#L86-L90

or `virtual-slides` ?

Thanks.

**Comment by nolimits4web** [comment]
both are correct and will work
