### ISSUE TITLE
Why was the `at` icon added again?

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#520]
@nolimits4web In commit https://github.com/framework7io/framework7-website/commit/cbb1744253665056cef8eac575d9d35d2343d15b the `at` icon has been added again. Why?

https://github.com/framework7io/framework7-website/blob/cbb1744253665056cef8eac575d9d35d2343d15b/build/manifest-icons.json#L517-L522

Thanks.

**Comment by nolimits4web** [comment]
Please, no questions in GH issues
