### ISSUE TITLE
Cannot create account on forum

### ISSUE THREAD

**Issue by garyrob** [framework7io/framework7-website#521]
Hello, I am having a maddening problem where I'm trying to sign up for the forum at https://forum.framework7.io but can't because I get a message that says "New registrations are not allowed from your IP address." There's nothing wrong with my IP, I'm using a mainstream phone company in Maine, USA for my internet. I tried from both Firefox and Safari, getting the same result. My IP is 72.87.56.208. I have absolutely no problems with any other web site.

Just in case it would help, I also tried using a VPN which would put my IP address in New Jersey. That didn't work either.

**Comment by nolimits4web** [comment]
More likely your IP (or similar) got into blacklist, I cleaned it up. Try again

**Comment by garyrob** [comment]
Yep that worked, thank you
