### ISSUE TITLE
The new `sortableMove` event is missing from the documentation 

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#527]
The new `sortableMove`, introduced in version 6.3.10 released today, is missing from the documentation:

- https://framework7.io/docs/sortable-list#sortable-events
- https://framework7.io/vue/sortable
- https://framework7.io/react/sortable
- https://framework7.io/svelte/sortable

Thanks.

**Comment by nolimits4web** [comment]
Don't hurry, please, I am working on it

**Comment by nolimits4web** [comment]
added
