### ISSUE TITLE
Tutorial  for framework 7 with meteor 

### ISSUE THREAD

**Issue by lastday4you** [framework7io/framework7-website#53]
i had wrote a tutorial on medium, i wanted to add it to the website. i saw the website that i need to open a pull request but where do i put my link in the tutorial folders? 
here is my link https://medium.com/@laykeanghok/building-hybrid-apps-with-meteor-framework-7-getting-started-e47d086f5b16

**Comment by nolimits4web** [comment]
Can you please add it to this file https://github.com/framework7io/framework7-website/blob/master/src/jade/tutorials/index.jade
