### ISSUE TITLE
Forum Login / Signup issue

### ISSUE THREAD

**Issue by onlyspike** [framework7io/framework7-website#542]
Wasnt sure on where to post this.
I tried to log into the Forum (https://forum.framework7.io/) but got the below error.
"You can't log in from that IP address."

I then tried to sign up with a new account to post this issue, but then got this error. "New registrations are not allowed from your IP address."

Any idea why I would get this error?

**Comment by nolimits4web** [comment]
your IP probably got banned by Forum, I cleaned the blocked IPs, you can try again

**Comment by onlyspike** [comment]
Thank you. It is working.
