### ISSUE TITLE
There are differences in the structure of the Package

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#557]
There are differences in the structure of the Package regarding the folders between what is described on page https://framework7.io/docs/package and what is present on https://unpkg.com/browse/framework7@7.0.1/

![Schermata 2022-04-24 alle 10 40 15](https://user-images.githubusercontent.com/1197819/164968317-ee68e8c0-83c4-4bcc-8ad2-d4a8838055a4.png)

![Schermata 2022-04-24 alle 10 40 50](https://user-images.githubusercontent.com/1197819/164968326-a49e4632-0d5f-45aa-ac92-18e2046024f3.png)

Thanks.

**Comment by nolimits4web** [comment]
What is not documented not intended to use

**Comment by DAnn2012** [comment]
@nolimits4web 
Thank you for the clarification.

But specifically I was referring to the lack of the "**types**" folder on unpkg.com, while in version 6.x it is present:

https://unpkg.com/browse/framework7@6.3.17/

![Schermata 2022-04-24 alle 11 23 36](https://user-images.githubusercontent.com/1197819/164969780-b440daa8-41f7-4b86-8e99-528ab4bf459f.png)
