### ISSUE TITLE
The Cards demo files in the Public folder are not updated to the latest version

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#565]
The following demo files of Cards present in "`/public/docs-demos/`" are not updated to the latest version with the changes I sent a few days ago (https://github.com/framework7io/framework7-website/commit/2448c4e7549ed63e647214dbdcaf4ce3c001db11) and which are present in "`/src/pug/docs-demos/`":

- https://github.com/framework7io/framework7-website/blob/master/public/docs-demos/core/cards_f7.html
- https://github.com/framework7io/framework7-website/blob/master/public/docs-demos/react/cards.js
- https://github.com/framework7io/framework7-website/blob/master/public/docs-demos/svelte/cards.js
- https://github.com/framework7io/framework7-website/blob/master/public/docs-demos/vue/cards.js

Thanks.

**Comment by nolimits4web** [comment]
should be fixed now
