### ISSUE TITLE
Problems with keyword highlighting in React's Color Pickers example

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#573]
Problems with keyword highlighting in [React's Color Pickers example](https://framework7.io/react/inputs#examples):

![color-pickes-examples](https://user-images.githubusercontent.com/1197819/170478222-7b18d1b4-ce0d-40db-8a0a-8c8fe2470db6.png)

Thanks.

**Comment by DAnn2012** [comment]
Hello @nolimits4web

as soon as you can, could you take a look at this problem?

Thanks.

**Comment by nolimits4web** [comment]
This is an issue withg 3rd party lib used for code highlighting, not going to dig into it or rework it
