### ISSUE TITLE
Demo of KS and safe areas

### ISSUE THREAD

**Issue by DAnn2012** [framework7io/framework7-website#614]
Hello @nolimits4web 

**Issue 1:**

In the KS demo on the home page there are the safe areas

![f7-s1](https://user-images.githubusercontent.com/1197819/229745303-f0d6f831-a0c2-4ba3-bde6-9383f5f624bd.png)

but changing the theme via the items in "Themes"

![f7-s2](https://user-images.githubusercontent.com/1197819/229745627-e337ca34-ef99-41df-ae14-8497cd9f7471.png)

safe areas disappear

![f7-s3](https://user-images.githubusercontent.com/1197819/229745708-047b0db0-6090-4238-834e-1649d9877fcf.png)

<hr>

**Issue 2:**

In the KS demo in the pages dedicated to it in Core, React, Svelte and Vue there are no safe areas

![f7-s4](https://user-images.githubusercontent.com/1197819/229746218-b8a2f842-26d6-408b-8c7f-8d9027f62b72.png)

while in the KS demo pages of framework7 version 7 there are the safe areas

![f7-s5](https://user-images.githubusercontent.com/1197819/229746547-017eb3ca-b101-46df-bc09-3300a081beb6.png)

Is this a change or something to fix?

Thanks.

**Comment by nolimits4web** [comment]
It is how it supposed to be

**Comment by DAnn2012** [comment]
Hello @nolimits4web 

Thank you for reply.

For "**Issue 2**" I can also understand it. But for "**Issue 1**" I just don't understand it.
