### ISSUE TITLE
Documentation for Smart Select recommends invalid HTML

### ISSUE THREAD

**Issue by ekwoka** [framework7io/framework7-website#628]
https://framework7.io/docs/smart-select

Here all the examples show an `a` tag around the `select`.

This is outside of spec.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#technical_summary

**Comment by nolimits4web** [comment]
And it is still valid and works totally fine everywhere

**Comment by ekwoka** [comment]
So you disagree with the HTML Working Group?

**Comment by ekwoka** [comment]
Also, it does NOT "work totally fine everywhere"

Example:

https://play.tailwindcss.com/gGIEhYd4j5

This produces two focusable elements that are indistinguishable when tabbing.

And for what?

what does an `a` do there that's useful? Why isn't it just a div? or span?

So to summarize:
1. It's out of spec to put a `select` inside an `a`
2. It creates two focusable elements, one of which won't really work
3. It adds nothing to the implementation over alternative element choices.
