### ISSUE TITLE
List our apps in Showcase

### ISSUE THREAD

**Issue by ViralTrivedi** [framework7io/framework7-website#71]
Hi,

We would like some of our apps to be listed in Showcase. Below is the list of the apps that we developed: -
1. Sportlounge
Play store: https://play.google.com/store/apps/details?id=de.grad53.sportlounge
App store: https://itunes.apple.com/AE/app/id472957977

2. Kridapp academy
Play store: https://play.google.com/store/apps/details?id=com.eonian.kridappacademy
App store: https://itunes.apple.com/us/app/kridapp-academy/id1244709794?mt=8

3. Reelo
Play store: https://play.google.com/store/apps/details?id=com.eonian.reelo
App store: https://itunes.apple.com/mt/app/reelo-get-rewarded/id1195820317?mt=8

4. Kridapp
Play store: https://play.google.com/store/apps/details?id=com.eonian.kridapp

5. Neon sports academy
Play store: https://play.google.com/store/apps/details?id=com.eonian.neon
App store: https://itunes.apple.com/us/app/neon-sports-academy/id1253983206?mt=8

Please do let me know if you need any further details from our side.

Thank you.

**Comment by nolimits4web** [comment]
Hi, can you please send PR to this repo with your apps?

**Comment by rashnk** [comment]
app created with f7  https://play.google.com/store/apps/details?id=org.islamicmajlis.salahtimes , Please add

**Comment by Banakin** [comment]
You are supposed to add them yourself to a fork and then create a pull request in order to merge them and get them onto the website

**Comment by rashnk** [comment]
where should i add and how ?

**Comment by luigi37** [comment]
Hi, I was wondering the same.

I think you need to create a Fork.
Oncce you have a fork you can change the related file which I think is
https://github.com/framework7io/framework7-website/blob/b024d3de2d34ed9c5ffa4ee0541718c96dc9572f/src/pug/showcase/showcase-apps.yml
and submit your pull request
Framework7 team will, eventually, approve the PR and put it online

I didn't try myself but thanks for confirming if it works.

**Comment by rashnk** [comment]
thank you for this, but where did u get this info from, i have not found this anywhere in f7 docs

**Comment by luigi37** [comment]
Well, just my assumption :-) Thanks for confirming if it works

**Comment by hazasaad** [comment]
I would like to add my app in your showcase.
[Appstore:](https://itunes.apple.com/us/app/%D8%AD%D9%84/id1194820433?mt=8)
[playstore:] (https://play.google.com/store/apps/details?id=com.arapeak.solution)
