### ISSUE TITLE
Please add my App to Showcase

### ISSUE THREAD

**Issue by fbalaguera** [framework7io/framework7-website#73]
This is my App: IDEANDO (Spanish and English)
https://play.google.com/store/apps/details?id=com.enliveapps.ideando.free
https://play.google.com/store/apps/details?id=com.enliveapps.ideando

Thank you!

**Comment by nolimits4web** [comment]
Can you please send PR to this repo with your app?

**Comment by fbalaguera** [comment]
Fredy Balaguera
http://www.enliveapps.com

Ideando App Free Versión:
https://play.google.com/store/apps/details?id=com.enliveapps.ideando.free

Ideando App paid version:
https://play.google.com/store/apps/details?id=com.enliveapps.ideando
Screenshots (free and paid):
https://www.dropbox.com/s/jmv9xr9kv89fwta/2017-05-07%2018.52.39.png?dl=0
https://www.dropbox.com/s/hi953gs2td6l6wq/2017-05-07%2018.52.48.png?dl=0
https://www.dropbox.com/s/s4oaiw2ma33ti2s/2017-05-07%2018.52.59.png?dl=0
https://www.dropbox.com/s/0571s6kkxhmbsst/2017-05-07%2018.53.17.png?dl=0
https://www.dropbox.com/s/3c0ylp9mlte3geg/2017-05-07%2018.53.53.png?dl=0



Libros Gratis de Amazon Kindle Gratis (spanish)
https://play.google.com/store/apps/details?id=com.enliveapps.librosgratis
Screenshots:
https://www.dropbox.com/s/5zpp90xhxzw3tuv/2017-08-03%2021.29.15.png?dl=0
https://www.dropbox.com/s/6b8ueie2f4c6cj0/2017-08-03%2021.29.22.png?dl=0
https://www.dropbox.com/s/6b8ueie2f4c6cj0/2017-08-03%2021.29.22.png?dl=0

**Comment by nolimits4web** [comment]
But how about PR?

**Comment by fbalaguera** [comment]
I do not understand, what is PR?

**Comment by nolimits4web** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by fbalaguera** [comment]
I do not have :(
