### ISSUE TITLE
There is no docs for v1

### ISSUE THREAD

**Issue by frontenddeveloping** [framework7io/framework7-website#86]
It will be better to provide v1 docs, not v2 only

**Comment by nolimits4web** [comment]
Have you seen this dropdown menu?

<img width="620" alt="v1" src="https://user-images.githubusercontent.com/999588/34827156-4fa27866-f6ea-11e7-9aa3-d8ff75eedfb8.png">

http://v1.framework7.io/

**Comment by frontenddeveloping** [comment]
@nolimits4web thank you, it was not clear for me, I clicked on Docs and get the v2 page
